"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {Inbox as InboxIcon,Send,BookUser,Hash,Settings,Copy,Share2,ArrowUpRight,Volume2,VolumeX,Wifi,WifiOff,Star,Trash2,ShieldBan,Flag,X,Check,Download,Radio,ChevronLeft,ChevronRight,Moon} from "lucide-react";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Toaster} from "@/components/ui/sonner";
import {toast} from "sonner";
import {Choice,Confirmation} from "./ppi-components/common";
import CallForm from "./ppi-components/call-form";
import Inbox from "./ppi-components/inbox";
import {Contacts,Codes} from "./ppi-components/manage";
import Preferences from "./ppi-components/preferences";
import {api,offlineStore,clearOffline,unlockAudio,beep,type Data,type Page} from "@/lib/ppi/client";
import {formatPager,meaningOf,inDnd} from "@/lib/ppi/shared";
const empty:Data={user:null,settings:{},pages:[],contacts:[],codes:[],blocks:[]};
export default function PagerApp({initialNumber=""}:{initialNumber?:string}){
 const [data,setData]=useState<Data>(empty),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(""),[busy,setBusy]=useState(false),[online,setOnline]=useState(true),[connection,setConnection]=useState("connecting"),[tab,setTab]=useState(initialNumber?"call":"inbox"),[target,setTarget]=useState(initialNumber),[selected,setSelected]=useState<string|null>(null),[detail,setDetail]=useState<string|null>(null),[name,setName]=useState(""),[share,setShare]=useState(false),[qr,setQr]=useState(""),[theme,setTheme]=useState("system"),[pulse,setPulse]=useState(false),[confirm,setConfirm]=useState<any>(null),[removeAccount,setRemoveAccount]=useState(false),[confirmNumber,setConfirmNumber]=useState(""),[report,setReport]=useState<string|null>(null),[reason,setReason]=useState(""),[installHelp,setInstallHelp]=useState(false),[help,setHelp]=useState(false);
 const dataRef=useRef(data),seen=useRef(new Set<string>()),installEvent=useRef<any>(null),pulseTimer=useRef<ReturnType<typeof setTimeout>|null>(null);dataRef.current=data;
 const reload=useCallback(async()=>{const d=await api("me");const fresh={...empty,...d};setData(fresh);setLoadError("");if(!fresh.user)await clearOffline().catch(()=>{});else{seen.current=new Set(fresh.pages.map((p:Page)=>p.id));await offlineStore({...fresh,pages:fresh.pages.slice(0,50),contacts:[],blocks:[],saved_at:Date.now()}).catch(()=>{})}return fresh},[]);
 useEffect(()=>{let live=true;setOnline(navigator.onLine);setTheme(localStorage.getItem("ppi-theme")||"system");reload().catch(async e=>{if(!live)return;if(!navigator.onLine){const cached=await offlineStore().catch(()=>null);if(cached){setData(cached);seen.current=new Set(cached.pages.map((p:Page)=>p.id));return}}setLoadError(e.message)}).finally(()=>live&&setLoading(false));const on=()=>{setOnline(true);void reload().catch(e=>setLoadError(e.message))},off=()=>{setOnline(false);setConnection("offline")},unlock=()=>void unlockAudio(),install=(e:Event)=>{e.preventDefault();installEvent.current=e};window.addEventListener("online",on);window.addEventListener("offline",off);window.addEventListener("pointerdown",unlock);window.addEventListener("keydown",unlock);window.addEventListener("beforeinstallprompt",install);if("serviceWorker"in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});return()=>{live=false;window.removeEventListener("online",on);window.removeEventListener("offline",off);window.removeEventListener("pointerdown",unlock);window.removeEventListener("keydown",unlock);window.removeEventListener("beforeinstallprompt",install)}},[reload]);
 useEffect(()=>{localStorage.setItem("ppi-theme",theme);const mq=matchMedia("(prefers-color-scheme: dark)");const apply=()=>document.documentElement.classList.toggle("dark",theme==="dark"||(theme==="system"&&mq.matches));apply();mq.addEventListener("change",apply);return()=>mq.removeEventListener("change",apply)},[theme]);
 useEffect(()=>{if(!data.user||!online)return;const es=new EventSource("/api/stream");es.onopen=()=>setConnection("connected");es.onerror=()=>setConnection("reconnecting");es.addEventListener("revoked",()=>{es.close();setData(empty);void clearOffline()});es.onmessage=e=>{try{const pages:Page[]=JSON.parse(e.data);const newcomers=pages.filter(p=>!seen.current.has(p.id)&&!p.read);seen.current=new Set(pages.map(p=>p.id));setData(d=>({...d,pages}));void offlineStore({...dataRef.current,pages:pages.slice(0,50),contacts:[],blocks:[],saved_at:Date.now()}).catch(()=>{});if(newcomers.length){setSelected(newcomers[0].id);setPulse(true);if(pulseTimer.current)clearTimeout(pulseTimer.current);pulseTimer.current=setTimeout(()=>setPulse(false),2500);const s=dataRef.current.settings;if(!inDnd(s)){if(s.sound)beep();if(s.vibration)try{navigator.vibrate?.([200,100,200])}catch{}}toast("새로운 삐삐가 도착했습니다.")}}catch{setConnection("reconnecting")}};return()=>es.close()},[data.user?.id,online]);
 const unread=data.pages.filter(p=>!p.read).length;
 useEffect(()=>{document.title=unread?`(${unread}) PPI — 새로운 신호`:'PPI — 말 대신, 숫자.';const nav=navigator as any;if(unread)nav.setAppBadge?.(unread)?.catch(()=>{});else nav.clearAppBadge?.()?.catch(()=>{})},[unread]);
 useEffect(()=>{if(!share||!data.user)return;let active=true;import("qrcode").then(m=>m.toDataURL(location.origin+"/call/"+data.user.pager_number,{width:240,margin:2,color:{dark:"#263d2b",light:"#ffffff"}})).then(src=>active&&setQr(src)).catch(()=>toast.error("QR 코드를 만들지 못했습니다."));return()=>{active=false}},[share,data.user?.pager_number]);
 useEffect(()=>{const model=(navigator as any).modelContext;if(!model?.registerTool)return;model.registerTool({name:"ppi_prepare_call",description:"PPI 호출 폼에 받는 사람 번호와 숫자 메시지를 준비합니다. 전송은 사용자가 호출하기 버튼으로 확인합니다.",inputSchema:{type:"object",properties:{pager_number:{type:"string"}},required:["pager_number"]},execute:async({pager_number}:{pager_number:string})=>{if(!/^015\d{8}$/.test(pager_number))throw new Error("Invalid pager number");setTarget(pager_number);setTab("call");return{content:[{type:"text",text:"호출 화면을 열었습니다. 회신 번호와 메시지를 입력하고 확인해 주세요."}]}});return()=>model.unregisterTool?.("ppi_prepare_call")},[]);
 async function mutate(path:string,method:string,b?:any,message?:string){if(!online){toast.error("연결된 상태에서 변경할 수 있습니다.");return false}if(busy)return false;setBusy(true);try{await api(path,method,b);await reload();if(message)toast.success(message);return true}catch(e){toast.error((e as Error).message);return false}finally{setBusy(false)}}
 async function copy(value:string){try{await navigator.clipboard.writeText(value);toast.success("복사했습니다.")}catch{toast.error("복사할 수 없습니다. 번호를 길게 눌러 복사해 주세요.")}}
 function call(n:string){setTarget(n);setTab("call");document.getElementById("workspace")?.scrollIntoView({behavior:"smooth",block:"start"})}
 const index=Math.max(0,data.pages.findIndex(p=>p.id===selected)),current=data.pages[index],opened=data.pages.find(p=>p.id===detail);const s=data.settings;const quiet=inDnd(s);
 function selectPage(p:Page){setSelected(p.id);setDetail(p.id);if(!p.read&&online)void mutate("pages/"+p.id,"PATCH",{read:true})}
 function browse(offset:number){if(!data.pages.length){toast("아직 받은 호출이 없습니다.");return}setSelected(data.pages[(index+offset+data.pages.length)%data.pages.length].id)}
 function install(){if(installEvent.current){void installEvent.current.prompt();installEvent.current=null}else setInstallHelp(true)}
 async function signup(e:React.FormEvent){e.preventDefault();if(await mutate("signup","POST",{username:name},"당신의 삐삐 번호가 발급되었습니다."))setTab(initialNumber?"call":"inbox")}
 const signInPath="/signin-with-chatgpt?return_to="+encodeURIComponent(initialNumber?"/call/"+initialNumber:"/");
 return <main className="studio"><Toaster position="top-center" richColors/><header><a href="/" aria-label="PPI 홈" className="brand">PPI<span>®</span></a><span>PERSONAL PAGING INTERFACE</span><div className="header-actions"><button className="text-button" onClick={()=>setHelp(true)}>이용 안내 <ArrowUpRight size={14}/></button><button className="icon-button" aria-label="다크모드 전환" onClick={()=>setTheme(document.documentElement.classList.contains("dark")?"light":"dark")}><Moon size={18}/></button></div></header>
 <section className="intro"><span className="eyebrow">다시, 우리만의 신호.</span><h1>말 대신, 숫자.</h1><p>짧은 숫자에 담아 보내는 마음. 당신의 삐삐가 기다리고 있어요.</p></section>
 {!online&&<div className="banner"><WifiOff size={16}/>오프라인입니다. 이 기기에 저장한 최근 호출을 보고 있어요.</div>}{loadError&&<div className="banner error" role="alert">{loadError}<button className="text-button" onClick={()=>{void reload().catch(e=>setLoadError(e.message))}}>다시 연결</button></div>}
 <div className="workspace" id="workspace"><section className="device-column"><div className="device-top"><span className="eyebrow">MY PAGER <span>/ 01</span></span><span className="connection">{data.user?(online?<Wifi size={13}/>:<WifiOff size={13}/>):<Radio size={13}/>} {data.user?(connection==="connected"?"수신 대기 중":online?"연결 중":"오프라인"):"당신의 신호를 기다립니다"}</span></div>
 <div className="desk"><div className={"pager "+(pulse?"receiving":"")}><div className="pager-brand">PPI <small>NUMERIC PAGER / 01</small><span className={"led "+(unread?"active":"")}/></div><div className="lcd" aria-live="polite" role="status"><div className="lcd-top"><span>{current?"CALL":"STANDBY"} {current&&new Date(current.created_at).toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit",hour12:false})}</span><span>{quiet?"DND":s.sound===0?"MUTE":"♪"} ▰</span></div><div className={"digits "+(current?.numeric_message.length>12?"long":"")}>{current?.numeric_message||(data.user?"00":"HELLO")}</div><div className="lcd-meaning">{current&&s.auto_decode?meaningOf(current.numeric_message,data.codes):current?" ":"새로운 신호를 기다리는 중"}</div><div className="lcd-bottom"><span>{current?.callback_number||(data.user?formatPager(data.user.pager_number):"YOUR LITTLE CONNECTION")}</span><span>{current?`${index+1}/${data.pages.length}`:"—"}</span></div></div><div className="pager-controls"><span>DIGITAL RECEIVER</span><button aria-label="이전 호출" onClick={()=>browse(-1)}><ChevronLeft size={17}/></button><button aria-label="선택한 호출 열기" onClick={()=>current?selectPage(current):toast("호출이 도착하면 여기서 확인할 수 있어요.")}>●</button><button aria-label="다음 호출" onClick={()=>browse(1)}><ChevronRight size={17}/></button></div><div className="pager-bottom"><span>WIDE AREA • PERSONAL MESSAGING</span><span className="speaker">▥▥▥</span></div></div></div>
 <div className="device-hint"><span>◀ ▶ 이전·다음 호출</span><span>● 호출 자세히 보기</span></div>
 {loading?<div className="number-card"><p>삐삐를 연결하고 있어요…</p></div>:data.user?<><div className="number-card"><div className="row-between"><span className="eyebrow">{data.user.username}님의 삐삐 번호</span><button aria-label="내 삐삐 번호 복사" className="icon-button" onClick={()=>void copy(data.user.pager_number)}><Copy size={16}/></button></div><div className="own-number">{formatPager(data.user.pager_number)}</div><div className="row-between"><Choice label="나의 상태" value={data.user.status} onChange={status=>void mutate("profile","PATCH",{status})} options={[{value:"available",label:"● 연락 가능"},{value:"later",label:"◌ 나중에 연락"},{value:"busy",label:"◌ 바쁨"}]}/><button className="text-button" onClick={()=>setShare(true)}><Share2 size={15}/>번호 공유</button></div></div><div className="device-stats"><span><i className="status-dot"/>{unread}개의 새 호출</span><button className="text-button" disabled={busy||!online} onClick={()=>{void unlockAudio();void mutate("settings","PATCH",{sound:!s.sound})}}>{s.sound?<Volume2 size={15}/>:<VolumeX size={15}/>}소리 {s.sound?"켜짐":"꺼짐"}</button></div></>:<div className="number-card onboarding"><span className="eyebrow">A NUMBER OF YOUR OWN</span><h2>당신만의 삐삐를 켜세요.</h2>{data.identity?.signedIn?<form onSubmit={signup} className="form-stack"><label>어떻게 불러드릴까요?<input aria-label="가입 이름" value={name} onChange={e=>setName(e.target.value)} placeholder="나의 이름 또는 별명" required maxLength={30}/></label><button className="primary full" disabled={busy||!online}>내 삐삐 번호 발급받기 <ArrowUpRight size={16}/></button></form>:<><p>로그인하면 고유한 번호가 생겨요.<br/>번호를 나누고 작은 신호를 주고받으세요.</p><a className="primary full" href={signInPath} target="_top">ChatGPT로 시작하기 <ArrowUpRight size={16}/></a></>}<small>호출만 보낼 때는 가입하지 않아도 괜찮아요.</small></div>}
 <div className="margin-note"><span>01 — KEEP IN TOUCH</span><p>길게 말하지 않아도<br/>마음은 전해지니까.</p></div></section>
 <section className="app-panel">{data.user?<Tabs value={tab} onValueChange={setTab}><TabsList className="main-tabs" variant="line">{[{v:"inbox",text:"받은 호출",icon:InboxIcon},{v:"call",text:"호출하기",icon:Send},{v:"contacts",text:"연락처",icon:BookUser},{v:"codes",text:"암호",icon:Hash},{v:"settings",text:"설정",icon:Settings}].map(t=><TabsTrigger value={t.v} key={t.v}><t.icon size={16}/><span>{t.text}</span>{t.v==="inbox"&&unread>0&&<i className="count">{unread}</i>}</TabsTrigger>)}</TabsList><TabsContent value="inbox"><Inbox pages={data.pages} codes={data.codes} decode={!!s.auto_decode} onSelect={selectPage} selected={selected||undefined}/></TabsContent><TabsContent value="call"><CallForm initialNumber={target} ownNumber={data.user.pager_number} online={online} contacts={data.contacts}/></TabsContent><TabsContent value="contacts"><Contacts contacts={data.contacts} mutate={mutate} busy={busy||!online} onCall={call}/></TabsContent><TabsContent value="codes"><Codes codes={data.codes} mutate={mutate} busy={busy||!online}/></TabsContent><TabsContent value="settings"><Preferences data={data} mutate={mutate} busy={busy||!online} theme={theme} onTheme={setTheme} onDelete={()=>setRemoveAccount(true)} install={install}/></TabsContent></Tabs>:<><div className="guest-tab"><Send size={16}/>호출하기<span>누구나 보낼 수 있어요</span></div><CallForm initialNumber={initialNumber} online={online}/></>}</section></div>
 <footer><span>작은 신호, 오래 남는 마음.</span><div><button className="text-button" onClick={install}>PPI 설치 <Download size={13}/></button><span>EST. 2026 · INSPIRED BY 1990</span></div></footer>
 <Dialog open={!!detail} onOpenChange={v=>!v&&setDetail(null)}><DialogContent className="modal"><DialogTitle>도착한 신호</DialogTitle><DialogDescription>{opened&&new Date(opened.created_at).toLocaleString("ko-KR")} · {opened?.read?"읽음":"안 읽음"}</DialogDescription>{opened&&<><div className="detail-lcd"><b>{opened.numeric_message}</b>{!!s.auto_decode&&<p>{meaningOf(opened.numeric_message,data.codes)}</p>}</div><div className="detail-callback"><small>회신 번호 · 발신자가 직접 입력한 번호입니다</small><b>{opened.callback_number}</b><button className="text-button" onClick={()=>void copy(opened.callback_number)}><Copy size={14}/>복사</button></div><div className="detail-actions"><button className="secondary" disabled={busy||!online} onClick={()=>void mutate("pages/"+opened.id,"PATCH",{favorite:!opened.favorite})}><Star size={16} fill={opened.favorite?"currentColor":"none"}/>{opened.favorite?"즐겨찾기 해제":"즐겨찾기"}</button><button className="secondary" disabled={busy||!online} onClick={()=>void mutate("pages/"+opened.id,"PATCH",{read:!opened.read})}><Check size={16}/>{opened.read?"안 읽음으로":"읽음 처리"}</button></div><div className="detail-actions minor"><button className="text-button" disabled={busy||!online} onClick={()=>setConfirm({title:"이 발신자를 차단할까요?",description:"가입 사용자는 계정 기준, 비회원은 네트워크 기준으로 차단합니다.",run:()=>void mutate("blocks","POST",{page_id:opened.id},"발신자를 차단했습니다.")})}><ShieldBan size={15}/>차단</button><button className="text-button" disabled={busy||!online} onClick={()=>{setReport(opened.id);setReason("")}}><Flag size={15}/>신고</button><button className="text-button danger" disabled={busy||!online} onClick={()=>setConfirm({title:"이 호출을 삭제할까요?",description:"삭제한 호출은 되돌릴 수 없습니다.",run:async()=>{if(await mutate("pages/"+opened.id,"DELETE",{},"호출을 삭제했습니다."))setDetail(null)}})}><Trash2 size={15}/>삭제</button></div></>}</DialogContent></Dialog>
 <Dialog open={share} onOpenChange={setShare}><DialogContent className="modal share-modal"><DialogTitle>내 삐삐를 불러주세요.</DialogTitle><DialogDescription>QR 코드나 링크를 친구에게 보내세요.</DialogDescription>{qr&&<img src={qr} width={240} height={240} alt="내 삐삐 호출 링크 QR 코드"/>}<b className="own-number">{formatPager(data.user?.pager_number)}</b><button className="primary" onClick={async()=>{const url=location.origin+"/call/"+data.user.pager_number;try{if(navigator.share)await navigator.share({title:"PPI — 내 삐삐를 불러주세요",url});else await copy(url)}catch(e){if((e as Error).name!=="AbortError")await copy(url)}}}><Share2 size={16}/>호출 링크 공유</button><button className="text-button" onClick={()=>void copy(location.origin+"/call/"+data.user.pager_number)}><Copy size={14}/>링크 복사</button></DialogContent></Dialog>
 <Dialog open={!!report} onOpenChange={v=>!v&&setReport(null)}><DialogContent className="modal"><DialogTitle>호출 신고</DialogTitle><DialogDescription>신고 내용은 운영 검토를 위해 저장됩니다. 즉시 수신을 막으려면 발신자도 차단해 주세요.</DialogDescription><form className="form-stack" onSubmit={async e=>{e.preventDefault();if(await mutate("reports","POST",{page_id:report,reason},"신고를 접수했습니다."))setReport(null)}}><label>신고 사유<textarea aria-label="신고 사유" required maxLength={300} value={reason} onChange={e=>setReason(e.target.value)} placeholder="어떤 문제가 있었나요?"/></label><button className="primary" disabled={busy}>신고 접수</button></form></DialogContent></Dialog>
 <Dialog open={removeAccount} onOpenChange={setRemoveAccount}><DialogContent className="modal"><DialogTitle>삐삐 계정을 삭제할까요?</DialogTitle><DialogDescription>내 번호·받은 호출·연락처·설정·암호가 영구 삭제됩니다. 다른 사람에게 이미 보낸 호출은 익명으로 남습니다. 확인을 위해 내 삐삐 번호를 입력하세요.</DialogDescription><form className="form-stack" onSubmit={async e=>{e.preventDefault();if(await mutate("account","DELETE",{confirm:confirmNumber.replace(/\D/g,"")},"계정을 삭제했습니다.")){await clearOffline();const r=await navigator.serviceWorker?.getRegistration();await (await r?.pushManager?.getSubscription())?.unsubscribe();setRemoveAccount(false);window.location.href="/signout-with-chatgpt?return_to=/"}}}><input aria-label="계정 삭제 확인 번호" inputMode="numeric" value={confirmNumber} onChange={e=>setConfirmNumber(e.target.value)} placeholder={formatPager(data.user?.pager_number)} required/><button className="primary destructive" disabled={busy||confirmNumber.replace(/\D/g,"")!==data.user?.pager_number}>계정 영구 삭제</button></form></DialogContent></Dialog>
 <Dialog open={installHelp} onOpenChange={setInstallHelp}><DialogContent className="modal"><DialogTitle>삐삐를 홈 화면에.</DialogTitle><DialogDescription>이 기기에 설치해서 더 편하게 호출을 받아보세요.</DialogDescription><div className="help-copy"><h3>iPhone · iPad</h3><p>Safari에서 이 사이트를 연 뒤 공유 메뉴 → ‘홈 화면에 추가’를 선택하세요. 설치한 앱에서 설정 → 푸시 알림을 켜 주세요.</p><h3>Android · PC</h3><p>Chrome 또는 Edge의 메뉴에서 ‘앱 설치’ 또는 ‘홈 화면에 추가’를 선택하세요. 설치 메뉴가 없다면 브라우저 탭에서도 사용할 수 있습니다.</p><p className="fineprint">오프라인에서는 이 기기에 저장된 최근 50개 호출을 볼 수 있어요. 공용 기기에서는 사용 후 로그아웃해 주세요.</p></div></DialogContent></Dialog>
 <Dialog open={help} onOpenChange={setHelp}><DialogContent className="modal"><DialogTitle>PPI 사용 안내</DialogTitle><DialogDescription>서로의 번호로 주고받는 작은 신호.</DialogDescription><div className="help-copy"><h3>01. 나만의 번호를 받으세요.</h3><p>ChatGPT로 로그인하고 이름을 정하면 고유한 삐삐 번호가 발급됩니다. 내 번호 옆 공유 버튼으로 링크와 QR을 보낼 수 있어요.</p><h3>02. 숫자로 마음을 전하세요.</h3><p>상대 번호와 회신 번호, 숫자 메시지를 입력하고 호출하세요. 기본 암호 외에 나만의 뜻을 등록할 수도 있습니다.</p><h3>03. 신호를 확인하세요.</h3><p>삐삐의 좌우 버튼으로 호출을 살펴보고 가운데 버튼으로 자세히 보세요. 소리는 화면을 한 번 누른 후부터 재생되며, 진동은 기기 지원 여부에 따라 달라집니다.</p><p className="fineprint">실제 전화망에 연결된 번호가 아닙니다. 회신 번호는 발신자가 입력한 값이므로 신원이 확인된 번호가 아닐 수 있습니다.</p></div></DialogContent></Dialog>
 <Confirmation action={confirm} onClose={()=>setConfirm(null)}/></main>
}
